import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1789510061277 implements MigrationInterface {
    name = 'InitialSchema1789510061277'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "acwr_thresholds" ("id_threshold" SERIAL NOT NULL, "low_min" numeric(4,2) NOT NULL DEFAULT '0.8', "low_max" numeric(4,2) NOT NULL DEFAULT '1.3', "medium_max" numeric(4,2) NOT NULL DEFAULT '1.5', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_63d42e85738d939620781dab84c" PRIMARY KEY ("id_threshold"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id_role" SERIAL NOT NULL, "name" character varying(50) NOT NULL, "code" character varying(50) NOT NULL, CONSTRAINT "PK_3ebdb96dd6787bda0e3c8f89d66" PRIMARY KEY ("id_role"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id_user" SERIAL NOT NULL, "id_role" integer NOT NULL, "name" character varying(100) NOT NULL, "lastname" character varying(100) NOT NULL, "email" character varying(150) NOT NULL, "password" character varying(255) NOT NULL, "birth_date" date, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_fbb07fa6fbd1d74bee9782fb945" PRIMARY KEY ("id_user"))`);
        await queryRunner.query(`CREATE TABLE "athletes_in_competencies" ("id_ath_comp" SERIAL NOT NULL, "id_user" integer NOT NULL, "id_competency" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_e9df06fe24e6bf7a4fa1617cce3" PRIMARY KEY ("id_ath_comp"))`);
        await queryRunner.query(`CREATE TABLE "matches" ("id_match" SERIAL NOT NULL, "id_competency" integer NOT NULL, "id_category" integer NOT NULL, "date" date NOT NULL, "time" TIME NOT NULL, "location" character varying NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a624257fb8a63c6433eb0daaf6e" PRIMARY KEY ("id_match"))`);
        await queryRunner.query(`CREATE TYPE "public"."seasons_status_enum" AS ENUM('planned', 'active', 'closed')`);
        await queryRunner.query(`CREATE TABLE "seasons" ("id_season" SERIAL NOT NULL, "name" character varying(50) NOT NULL, "start_date" date NOT NULL, "end_date" date, "status" "public"."seasons_status_enum" NOT NULL DEFAULT 'planned', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_873970e34b625e685a37e59956f" PRIMARY KEY ("id_season"))`);
        await queryRunner.query(`CREATE TABLE "competencies" ("id_competency" SERIAL NOT NULL, "id_category" integer NOT NULL, "name" character varying NOT NULL, "description" character varying, "start_date" TIMESTAMP NOT NULL, "finish_date" TIMESTAMP, "id_season" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "REL_2e997c54d1f697b1202bee5215" UNIQUE ("id_category"), CONSTRAINT "PK_82bd4a1c9db1e60ced4cc126852" PRIMARY KEY ("id_competency"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id_category" SERIAL NOT NULL, "name" character varying(100) NOT NULL, "min_age" integer NOT NULL, "max_age" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_8ac255b9743120147e61fb5465b" PRIMARY KEY ("id_category"))`);
        await queryRunner.query(`CREATE TABLE "athletes_in_categories" ("id_ath_cat" SERIAL NOT NULL, "id_user" integer NOT NULL, "id_category" integer NOT NULL, "id_season" integer, "position" character varying(30), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_042bc5419f59b92250937883195" PRIMARY KEY ("id_ath_cat"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_athletes_in_categories_user_category_legacy" ON "athletes_in_categories"  ("id_user", "id_category") WHERE id_season IS NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_athletes_in_categories_user_season" ON "athletes_in_categories"  ("id_user", "id_season") WHERE id_season IS NOT NULL`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id_refresh_token" SERIAL NOT NULL, "id_user" integer NOT NULL, "token_hash" character varying(64) NOT NULL, "family" character varying(36) NOT NULL, "revoked" boolean NOT NULL DEFAULT false, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "ip" character varying(45), "user_agent" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_a7838d2ba25be1342091b6695f1" UNIQUE ("token_hash"), CONSTRAINT "PK_2c0b8d8915327252ab5ff2b53fc" PRIMARY KEY ("id_refresh_token"))`);
        await queryRunner.query(`CREATE TYPE "public"."development_objectives_status_enum" AS ENUM('open', 'achieved', 'missed')`);
        await queryRunner.query(`CREATE TABLE "development_objectives" ("id_objective" SERIAL NOT NULL, "id_user" integer NOT NULL, "id_season" integer NOT NULL, "description" text NOT NULL, "target_date" date NOT NULL, "status" "public"."development_objectives_status_enum" NOT NULL DEFAULT 'open', "set_by" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_3a331365e69b781f1038fe32b9a" PRIMARY KEY ("id_objective"))`);
        await queryRunner.query(`CREATE TYPE "public"."fatigue_alerts_level_enum" AS ENUM('bajo', 'medio', 'alto')`);
        await queryRunner.query(`CREATE TYPE "public"."fatigue_alerts_status_enum" AS ENUM('open', 'reviewed', 'dismissed')`);
        await queryRunner.query(`CREATE TABLE "fatigue_alerts" ("id_alert" SERIAL NOT NULL, "id_user" integer NOT NULL, "date" date NOT NULL, "acute_load" numeric(8,2) NOT NULL, "chronic_load" numeric(8,2) NOT NULL, "acwr_value" numeric(4,2) NOT NULL, "rpe_avg" numeric(3,1) NOT NULL, "level" "public"."fatigue_alerts_level_enum" NOT NULL, "status" "public"."fatigue_alerts_status_enum" NOT NULL DEFAULT 'open', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1f713af20d1bfecd54bd32494bf" PRIMARY KEY ("id_alert"))`);
        await queryRunner.query(`CREATE TYPE "public"."health_records_status_enum" AS ENUM('active', 'resolved')`);
        await queryRunner.query(`CREATE TABLE "health_records" ("id_health" SERIAL NOT NULL, "id_user" integer NOT NULL, "condition_type" character varying(60) NOT NULL, "description" text NOT NULL, "restriction" boolean NOT NULL DEFAULT false, "status" "public"."health_records_status_enum" NOT NULL DEFAULT 'active', "registered_by" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_8d39a619aaae6caa41d337f0f2c" PRIMARY KEY ("id_health"))`);
        await queryRunner.query(`CREATE TYPE "public"."health_record_access_logs_action_enum" AS ENUM('list', 'read', 'create', 'update', 'delete')`);
        await queryRunner.query(`CREATE TABLE "health_record_access_logs" ("id_log" SERIAL NOT NULL, "id_health" integer, "accessed_by" integer NOT NULL, "action" "public"."health_record_access_logs_action_enum" NOT NULL, "accessed_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_36414a45e278a99d2e7ea2da29d" PRIMARY KEY ("id_log"))`);
        await queryRunner.query(`CREATE TYPE "public"."injuries_severity_enum" AS ENUM('leve', 'moderada', 'severa')`);
        await queryRunner.query(`CREATE TYPE "public"."injuries_status_enum" AS ENUM('active', 'recovering', 'recovered')`);
        await queryRunner.query(`CREATE TABLE "injuries" ("id_injury" SERIAL NOT NULL, "id_user" integer NOT NULL, "injury_date" date NOT NULL, "body_part" character varying(50) NOT NULL, "severity" "public"."injuries_severity_enum" NOT NULL, "diagnosis" text, "recovery_date" date, "status" "public"."injuries_status_enum" NOT NULL DEFAULT 'active', "registered_by" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_9a3b0773b6defd8f210fc2fce6d" PRIMARY KEY ("id_injury"))`);
        await queryRunner.query(`CREATE TYPE "public"."injury_risk_assessments_method_enum" AS ENUM('rules', 'ml_model')`);
        await queryRunner.query(`CREATE TYPE "public"."injury_risk_assessments_risk_level_enum" AS ENUM('bajo', 'medio', 'alto')`);
        await queryRunner.query(`CREATE TYPE "public"."injury_risk_assessments_status_enum" AS ENUM('open', 'reviewed', 'dismissed')`);
        await queryRunner.query(`CREATE TABLE "injury_risk_assessments" ("id_assessment" SERIAL NOT NULL, "id_user" integer NOT NULL, "assessment_date" date NOT NULL, "method" "public"."injury_risk_assessments_method_enum" NOT NULL, "risk_level" "public"."injury_risk_assessments_risk_level_enum" NOT NULL, "triggered_rules" text NOT NULL, "details" text, "acwr_value" numeric(4,2), "status" "public"."injury_risk_assessments_status_enum" NOT NULL DEFAULT 'open', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_93216dd460daf786ce40683f394" PRIMARY KEY ("id_assessment"))`);
        await queryRunner.query(`CREATE TABLE "injury_risk_rule_configs" ("id_config" SERIAL NOT NULL, "sustained_acwr_threshold" numeric(4,2) NOT NULL DEFAULT '1.5', "sustained_acwr_min_days" integer NOT NULL DEFAULT '2', "sustained_acwr_lookback_days" integer NOT NULL DEFAULT '7', "sustained_rpe_threshold" smallint NOT NULL DEFAULT '8', "sustained_rpe_min_sessions" integer NOT NULL DEFAULT '3', "sustained_rpe_lookback_days" integer NOT NULL DEFAULT '14', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1d0b4687804f506904e1ce6008a" PRIMARY KEY ("id_config"))`);
        await queryRunner.query(`CREATE TABLE "match_statistics" ("id_match_stat" SERIAL NOT NULL, "id_match" integer NOT NULL, "id_user" integer NOT NULL, "minutes_played" integer NOT NULL, "goals" smallint NOT NULL DEFAULT '0', "assists" smallint NOT NULL DEFAULT '0', "yellow_cards" smallint NOT NULL DEFAULT '0', "red_cards" smallint NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a89f873cd6d56398ba7a32d5f1e" PRIMARY KEY ("id_match_stat"))`);
        await queryRunner.query(`CREATE TYPE "public"."parental_consents_status_enum" AS ENUM('pending', 'granted', 'revoked')`);
        await queryRunner.query(`CREATE TABLE "parental_consents" ("id_consent" SERIAL NOT NULL, "id_user" integer NOT NULL, "guardian_name" character varying(150) NOT NULL, "guardian_document" character varying(30) NOT NULL, "guardian_relationship" character varying(40) NOT NULL, "signed_at" TIMESTAMP WITH TIME ZONE NOT NULL, "document_url" character varying(255), "status" "public"."parental_consents_status_enum" NOT NULL DEFAULT 'pending', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6dfe344969995532195c2d46c8d" PRIMARY KEY ("id_consent"))`);
        await queryRunner.query(`CREATE TYPE "public"."physical_evaluations_stage_enum" AS ENUM('pre', 'mid', 'post')`);
        await queryRunner.query(`CREATE TYPE "public"."physical_evaluations_test_method_enum" AS ENUM('course_navette', 'cooper', 'otro')`);
        await queryRunner.query(`CREATE TABLE "physical_evaluations" ("id_eval" SERIAL NOT NULL, "id_user" integer NOT NULL, "id_season" integer NOT NULL, "stage" "public"."physical_evaluations_stage_enum" NOT NULL, "height_cm" numeric(5,2) NOT NULL, "weight_kg" numeric(5,2) NOT NULL, "vo2max_estimado" numeric(5,2), "test_method" "public"."physical_evaluations_test_method_enum", "speed_20m" numeric(5,2), "eval_date" date NOT NULL, "evaluator_id" integer, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7ad6a3dfb468f9a73422227764b" PRIMARY KEY ("id_eval"))`);
        await queryRunner.query(`CREATE TABLE "position_weight_profiles" ("id_profile" SERIAL NOT NULL, "position" character varying(50) NOT NULL, "age_category" character varying(100) NOT NULL, "w_physical" numeric(3,2) NOT NULL, "w_technical" numeric(3,2) NOT NULL, "w_participation" numeric(3,2) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_84637a5be4060c08bea0ce0fa60" PRIMARY KEY ("id_profile"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_position_weight_profiles_position_age_category" ON "position_weight_profiles"  ("position", "age_category") `);
        await queryRunner.query(`CREATE TABLE "technical_evaluations" ("id_eval_tech" SERIAL NOT NULL, "id_user" integer NOT NULL, "id_season" integer NOT NULL, "indicator" character varying(60) NOT NULL, "score" numeric(3,1) NOT NULL, "evaluator_id" integer NOT NULL, "eval_date" date NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_122583ef5ffa6e928bd55f8a9fe" PRIMARY KEY ("id_eval_tech"))`);
        await queryRunner.query(`CREATE TYPE "public"."talent_flags_status_enum" AS ENUM('open', 'reviewed', 'dismissed')`);
        await queryRunner.query(`CREATE TABLE "talent_flags" ("id_flag" SERIAL NOT NULL, "id_user" integer NOT NULL, "id_season" integer NOT NULL, "criteria" text NOT NULL, "recommended_action" text NOT NULL, "status" "public"."talent_flags_status_enum" NOT NULL DEFAULT 'open', "created_by" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7751a3f9432a35c1bb0b3590df7" PRIMARY KEY ("id_flag"))`);
        await queryRunner.query(`CREATE TYPE "public"."training_sessions_type_enum" AS ENUM('tecnico', 'fisico', 'tactico', 'mixto')`);
        await queryRunner.query(`CREATE TABLE "training_sessions" ("id_session" SERIAL NOT NULL, "id_category" integer NOT NULL, "id_season" integer NOT NULL, "date" date NOT NULL, "type" "public"."training_sessions_type_enum" NOT NULL, "planned_duration_min" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_fe0580fda6aaaa897e9f6adb85d" PRIMARY KEY ("id_session"))`);
        await queryRunner.query(`CREATE TABLE "training_loads" ("id_load" SERIAL NOT NULL, "id_session" integer NOT NULL, "id_user" integer NOT NULL, "rpe" smallint NOT NULL, "duration_min" integer NOT NULL, "session_load" integer NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_a2bd3450eb5a64663c5d44bf3d0" PRIMARY KEY ("id_load"))`);
        await queryRunner.query(`CREATE TABLE "weighted_progress_indices" ("id_index" SERIAL NOT NULL, "id_user" integer NOT NULL, "id_season" integer NOT NULL, "id_profile" integer NOT NULL, "physical_score" numeric(5,2) NOT NULL, "technical_score" numeric(5,2) NOT NULL, "participation_score" numeric(5,2) NOT NULL, "index_value" numeric(5,2) NOT NULL, "warnings" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7985f3a09eace29d4f31ff0fa6d" PRIMARY KEY ("id_index"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_weighted_progress_index_user_season" ON "weighted_progress_indices"  ("id_user", "id_season") `);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_f8a3754f51a266a160e71d261f8" FOREIGN KEY ("id_role") REFERENCES "roles"("id_role") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "athletes_in_competencies" ADD CONSTRAINT "FK_d27606d6985203155119355c4d1" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "athletes_in_competencies" ADD CONSTRAINT "FK_1cd00f78e6280e1fe3c81ac4ff6" FOREIGN KEY ("id_competency") REFERENCES "competencies"("id_competency") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_99b560569cbc9b04264ac89306e" FOREIGN KEY ("id_competency") REFERENCES "competencies"("id_competency") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "matches" ADD CONSTRAINT "FK_7b714328e970521ea7668cc8602" FOREIGN KEY ("id_category") REFERENCES "categories"("id_category") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competencies" ADD CONSTRAINT "FK_2e997c54d1f697b1202bee52150" FOREIGN KEY ("id_category") REFERENCES "categories"("id_category") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "competencies" ADD CONSTRAINT "FK_50f11487a14669f1626985294b6" FOREIGN KEY ("id_season") REFERENCES "seasons"("id_season") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "athletes_in_categories" ADD CONSTRAINT "FK_b2d8a3068f1ea199a9d5c7d23ac" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "athletes_in_categories" ADD CONSTRAINT "FK_ab1f7f506edd6e4409890aa6b2c" FOREIGN KEY ("id_category") REFERENCES "categories"("id_category") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "athletes_in_categories" ADD CONSTRAINT "FK_42cb8004cc115975a97531dabdd" FOREIGN KEY ("id_season") REFERENCES "seasons"("id_season") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_4af71d2dec39fdef0aef90c9593" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "development_objectives" ADD CONSTRAINT "FK_259eea33cdc03abe2e8baaa0b3b" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "development_objectives" ADD CONSTRAINT "FK_4b92e55112811d9101dbec68157" FOREIGN KEY ("id_season") REFERENCES "seasons"("id_season") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "development_objectives" ADD CONSTRAINT "FK_96490209ea346f126a6bc7d9641" FOREIGN KEY ("set_by") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fatigue_alerts" ADD CONSTRAINT "FK_c767afcf8037b5bd66e9a2efb9b" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD CONSTRAINT "FK_808515cadd1cf3244f69f89a5af" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_records" ADD CONSTRAINT "FK_e4476519925f6e4e67ce2cce2bd" FOREIGN KEY ("registered_by") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_record_access_logs" ADD CONSTRAINT "FK_f3bc0e7614175e891f2677f1ca5" FOREIGN KEY ("id_health") REFERENCES "health_records"("id_health") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "health_record_access_logs" ADD CONSTRAINT "FK_d9ca5ca5778748300b4b1743415" FOREIGN KEY ("accessed_by") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "injuries" ADD CONSTRAINT "FK_627d2abd2a23494ac6ef08f0215" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "injuries" ADD CONSTRAINT "FK_b3b0febcece738b80f164cc94b6" FOREIGN KEY ("registered_by") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "injury_risk_assessments" ADD CONSTRAINT "FK_6573f6c48e58119a182699ba451" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_statistics" ADD CONSTRAINT "FK_063884763146db38f96447c69c9" FOREIGN KEY ("id_match") REFERENCES "matches"("id_match") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "match_statistics" ADD CONSTRAINT "FK_5aa16bbbfece9e6a5b8c87cc6b6" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "parental_consents" ADD CONSTRAINT "FK_66be32d1d133f6d5df7d4ff26fc" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "physical_evaluations" ADD CONSTRAINT "FK_9e5050de05d99f48a142a256884" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "physical_evaluations" ADD CONSTRAINT "FK_902969f2e08f3f4bddd977ee986" FOREIGN KEY ("id_season") REFERENCES "seasons"("id_season") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "physical_evaluations" ADD CONSTRAINT "FK_3cb1123eab52e2f921d39bc0e20" FOREIGN KEY ("evaluator_id") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "technical_evaluations" ADD CONSTRAINT "FK_24b4fc3c44de38f9c14c1126e27" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "technical_evaluations" ADD CONSTRAINT "FK_0dcba6fe6e031cb35c07f8ff79b" FOREIGN KEY ("id_season") REFERENCES "seasons"("id_season") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "technical_evaluations" ADD CONSTRAINT "FK_64b7d3bd5ac6b535217f484fd49" FOREIGN KEY ("evaluator_id") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "talent_flags" ADD CONSTRAINT "FK_2ee4b1e6d14fdfa699bc78be06d" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "talent_flags" ADD CONSTRAINT "FK_f994460e94d903bbaec7d6bad42" FOREIGN KEY ("id_season") REFERENCES "seasons"("id_season") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "talent_flags" ADD CONSTRAINT "FK_b8b9c1ede5a8c8b5d1f08e71283" FOREIGN KEY ("created_by") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "training_sessions" ADD CONSTRAINT "FK_9403234da6aa32054133f866633" FOREIGN KEY ("id_category") REFERENCES "categories"("id_category") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "training_sessions" ADD CONSTRAINT "FK_5967d53f9ebfee50a8a5e382f88" FOREIGN KEY ("id_season") REFERENCES "seasons"("id_season") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "training_loads" ADD CONSTRAINT "FK_39e0e2ca94075c6a7b4772f2e5c" FOREIGN KEY ("id_session") REFERENCES "training_sessions"("id_session") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "training_loads" ADD CONSTRAINT "FK_c821af45b8322862fb8dcf22a20" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "weighted_progress_indices" ADD CONSTRAINT "FK_fbb87af7347cb4e21d108c75233" FOREIGN KEY ("id_user") REFERENCES "users"("id_user") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "weighted_progress_indices" ADD CONSTRAINT "FK_afecfb60582eeaa1f540894a89c" FOREIGN KEY ("id_season") REFERENCES "seasons"("id_season") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "weighted_progress_indices" ADD CONSTRAINT "FK_5e5f78107488341b2c41d2f864c" FOREIGN KEY ("id_profile") REFERENCES "position_weight_profiles"("id_profile") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "weighted_progress_indices" DROP CONSTRAINT "FK_5e5f78107488341b2c41d2f864c"`);
        await queryRunner.query(`ALTER TABLE "weighted_progress_indices" DROP CONSTRAINT "FK_afecfb60582eeaa1f540894a89c"`);
        await queryRunner.query(`ALTER TABLE "weighted_progress_indices" DROP CONSTRAINT "FK_fbb87af7347cb4e21d108c75233"`);
        await queryRunner.query(`ALTER TABLE "training_loads" DROP CONSTRAINT "FK_c821af45b8322862fb8dcf22a20"`);
        await queryRunner.query(`ALTER TABLE "training_loads" DROP CONSTRAINT "FK_39e0e2ca94075c6a7b4772f2e5c"`);
        await queryRunner.query(`ALTER TABLE "training_sessions" DROP CONSTRAINT "FK_5967d53f9ebfee50a8a5e382f88"`);
        await queryRunner.query(`ALTER TABLE "training_sessions" DROP CONSTRAINT "FK_9403234da6aa32054133f866633"`);
        await queryRunner.query(`ALTER TABLE "talent_flags" DROP CONSTRAINT "FK_b8b9c1ede5a8c8b5d1f08e71283"`);
        await queryRunner.query(`ALTER TABLE "talent_flags" DROP CONSTRAINT "FK_f994460e94d903bbaec7d6bad42"`);
        await queryRunner.query(`ALTER TABLE "talent_flags" DROP CONSTRAINT "FK_2ee4b1e6d14fdfa699bc78be06d"`);
        await queryRunner.query(`ALTER TABLE "technical_evaluations" DROP CONSTRAINT "FK_64b7d3bd5ac6b535217f484fd49"`);
        await queryRunner.query(`ALTER TABLE "technical_evaluations" DROP CONSTRAINT "FK_0dcba6fe6e031cb35c07f8ff79b"`);
        await queryRunner.query(`ALTER TABLE "technical_evaluations" DROP CONSTRAINT "FK_24b4fc3c44de38f9c14c1126e27"`);
        await queryRunner.query(`ALTER TABLE "physical_evaluations" DROP CONSTRAINT "FK_3cb1123eab52e2f921d39bc0e20"`);
        await queryRunner.query(`ALTER TABLE "physical_evaluations" DROP CONSTRAINT "FK_902969f2e08f3f4bddd977ee986"`);
        await queryRunner.query(`ALTER TABLE "physical_evaluations" DROP CONSTRAINT "FK_9e5050de05d99f48a142a256884"`);
        await queryRunner.query(`ALTER TABLE "parental_consents" DROP CONSTRAINT "FK_66be32d1d133f6d5df7d4ff26fc"`);
        await queryRunner.query(`ALTER TABLE "match_statistics" DROP CONSTRAINT "FK_5aa16bbbfece9e6a5b8c87cc6b6"`);
        await queryRunner.query(`ALTER TABLE "match_statistics" DROP CONSTRAINT "FK_063884763146db38f96447c69c9"`);
        await queryRunner.query(`ALTER TABLE "injury_risk_assessments" DROP CONSTRAINT "FK_6573f6c48e58119a182699ba451"`);
        await queryRunner.query(`ALTER TABLE "injuries" DROP CONSTRAINT "FK_b3b0febcece738b80f164cc94b6"`);
        await queryRunner.query(`ALTER TABLE "injuries" DROP CONSTRAINT "FK_627d2abd2a23494ac6ef08f0215"`);
        await queryRunner.query(`ALTER TABLE "health_record_access_logs" DROP CONSTRAINT "FK_d9ca5ca5778748300b4b1743415"`);
        await queryRunner.query(`ALTER TABLE "health_record_access_logs" DROP CONSTRAINT "FK_f3bc0e7614175e891f2677f1ca5"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP CONSTRAINT "FK_e4476519925f6e4e67ce2cce2bd"`);
        await queryRunner.query(`ALTER TABLE "health_records" DROP CONSTRAINT "FK_808515cadd1cf3244f69f89a5af"`);
        await queryRunner.query(`ALTER TABLE "fatigue_alerts" DROP CONSTRAINT "FK_c767afcf8037b5bd66e9a2efb9b"`);
        await queryRunner.query(`ALTER TABLE "development_objectives" DROP CONSTRAINT "FK_96490209ea346f126a6bc7d9641"`);
        await queryRunner.query(`ALTER TABLE "development_objectives" DROP CONSTRAINT "FK_4b92e55112811d9101dbec68157"`);
        await queryRunner.query(`ALTER TABLE "development_objectives" DROP CONSTRAINT "FK_259eea33cdc03abe2e8baaa0b3b"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_4af71d2dec39fdef0aef90c9593"`);
        await queryRunner.query(`ALTER TABLE "athletes_in_categories" DROP CONSTRAINT "FK_42cb8004cc115975a97531dabdd"`);
        await queryRunner.query(`ALTER TABLE "athletes_in_categories" DROP CONSTRAINT "FK_ab1f7f506edd6e4409890aa6b2c"`);
        await queryRunner.query(`ALTER TABLE "athletes_in_categories" DROP CONSTRAINT "FK_b2d8a3068f1ea199a9d5c7d23ac"`);
        await queryRunner.query(`ALTER TABLE "competencies" DROP CONSTRAINT "FK_50f11487a14669f1626985294b6"`);
        await queryRunner.query(`ALTER TABLE "competencies" DROP CONSTRAINT "FK_2e997c54d1f697b1202bee52150"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_7b714328e970521ea7668cc8602"`);
        await queryRunner.query(`ALTER TABLE "matches" DROP CONSTRAINT "FK_99b560569cbc9b04264ac89306e"`);
        await queryRunner.query(`ALTER TABLE "athletes_in_competencies" DROP CONSTRAINT "FK_1cd00f78e6280e1fe3c81ac4ff6"`);
        await queryRunner.query(`ALTER TABLE "athletes_in_competencies" DROP CONSTRAINT "FK_d27606d6985203155119355c4d1"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_f8a3754f51a266a160e71d261f8"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_weighted_progress_index_user_season"`);
        await queryRunner.query(`DROP TABLE "weighted_progress_indices"`);
        await queryRunner.query(`DROP TABLE "training_loads"`);
        await queryRunner.query(`DROP TABLE "training_sessions"`);
        await queryRunner.query(`DROP TYPE "public"."training_sessions_type_enum"`);
        await queryRunner.query(`DROP TABLE "talent_flags"`);
        await queryRunner.query(`DROP TYPE "public"."talent_flags_status_enum"`);
        await queryRunner.query(`DROP TABLE "technical_evaluations"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_position_weight_profiles_position_age_category"`);
        await queryRunner.query(`DROP TABLE "position_weight_profiles"`);
        await queryRunner.query(`DROP TABLE "physical_evaluations"`);
        await queryRunner.query(`DROP TYPE "public"."physical_evaluations_test_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."physical_evaluations_stage_enum"`);
        await queryRunner.query(`DROP TABLE "parental_consents"`);
        await queryRunner.query(`DROP TYPE "public"."parental_consents_status_enum"`);
        await queryRunner.query(`DROP TABLE "match_statistics"`);
        await queryRunner.query(`DROP TABLE "injury_risk_rule_configs"`);
        await queryRunner.query(`DROP TABLE "injury_risk_assessments"`);
        await queryRunner.query(`DROP TYPE "public"."injury_risk_assessments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."injury_risk_assessments_risk_level_enum"`);
        await queryRunner.query(`DROP TYPE "public"."injury_risk_assessments_method_enum"`);
        await queryRunner.query(`DROP TABLE "injuries"`);
        await queryRunner.query(`DROP TYPE "public"."injuries_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."injuries_severity_enum"`);
        await queryRunner.query(`DROP TABLE "health_record_access_logs"`);
        await queryRunner.query(`DROP TYPE "public"."health_record_access_logs_action_enum"`);
        await queryRunner.query(`DROP TABLE "health_records"`);
        await queryRunner.query(`DROP TYPE "public"."health_records_status_enum"`);
        await queryRunner.query(`DROP TABLE "fatigue_alerts"`);
        await queryRunner.query(`DROP TYPE "public"."fatigue_alerts_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."fatigue_alerts_level_enum"`);
        await queryRunner.query(`DROP TABLE "development_objectives"`);
        await queryRunner.query(`DROP TYPE "public"."development_objectives_status_enum"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_athletes_in_categories_user_season"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_athletes_in_categories_user_category_legacy"`);
        await queryRunner.query(`DROP TABLE "athletes_in_categories"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "competencies"`);
        await queryRunner.query(`DROP TABLE "seasons"`);
        await queryRunner.query(`DROP TYPE "public"."seasons_status_enum"`);
        await queryRunner.query(`DROP TABLE "matches"`);
        await queryRunner.query(`DROP TABLE "athletes_in_competencies"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "acwr_thresholds"`);
    }

}
